# my global config
global:
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "mysql_exporter"
    metrics_path: /probe
    params:
      target: ['mysqld:3306']
    static_configs:
        - targets: ["mysql_exporter:9104"]